name: arch_generator
description: A CLI tool to generate Flutter clean architecture feature structures with boilerplate code.
version: 1.0.0
homepage: https://github.com/awshakam1998/arch_generator
repository: https://github.com/awshakam1998/arch_generator
issue_tracker: https://github.com/awshakam1998/arch_generator/issues

environment:
  sdk: ^3.10.3

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  path: ^1.9.0
  mason_logger: ^0.2.11

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

executables:
  arch_generator:
